server:
  port: 9010
spring:
  application:
    name: ourblog-gateway-center
  cloud:
    nacos:
      discovery:
        server-addr: http://139.159.134.136:8848,http://139.159.134.136:8849，http://139.159.134.136:8850 #配置Nacos地址
    gateway:
      routes: #配置路由路径
        - id: oauth2-auth-route
          uri: lb://ourblog-oauth2-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user-api-route          # 当前路由的标识, 要求唯一
          uri: lb://ourblog-user  # lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          predicates: # 断言(就是路由转发要满足的条件)
            - Path=/api/user/**       # 当请求路径满足Path指定的规则时,才进行路由转发
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1           # 转发之前去掉1层路径
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 1
    port: 6379
    host: 8.129.173.191
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/auth/oauth/token"
      - "/api/user/save"